steps:
  - name: "Install dependencies"
    command: 
    - "npm install --silent"
    - "npm run build"
    plugins:
      - docker#v3.8.0:
          image: "node:12"
  - name: "Docker Build"
    command:
    - "docker buildx ./"
  - name: "Docker Push"
    command: 
    - "docker push 377117578606.dkr.ecr.ap-southeast-2.amazonaws.com/buildkite-demo"
        plugins:
      - ecr#v2.4.0:
          login: true
