steps:


  - label: "Listing my files"
    command: "listing-files.sh"
    
  - name: "Install dependencies"
    command: 
    - "npm install --silent"
    - "npm run build"
    plugins:
      - docker#v3.8.0:
          image: "node:12"
  - name: "Docker Build"
    command:
    - "docker build ./"
 
